# Generated by Django 4.1.7 on 2025-02-09 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('headquarters', models.CharField(max_length=30)),
                ('company_size', models.CharField(choices=[('Micro', 'Até 19 colaboradores'), ('Pequena', '20 à 99 colaboradores'), ('Media', '100 à 499 colaboradores'), ('Grande', 'Acima de 500 colaboradores')], max_length=30)),
                ('marketing_niche', models.CharField(choices=[('Marketing', 'Marketing'), ('Tecnologia', 'Tecnologia'), ('Nutrição', 'Nutrição'), ('Design', 'Design')], max_length=30)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logo')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('url', models.URLField(max_length=300)),
                ('experience', models.CharField(choices=[('J', 'Júnior'), ('P', 'Pleno'), ('S', 'Sênior')], max_length=20)),
                ('final_date', models.DateField()),
                ('position_type', models.IntegerField()),
                ('status', models.CharField(choices=[('I', 'Interesse'), ('C', 'Currículo enviado'), ('E', 'Entrevista'), ('D', 'Desafio técnico'), ('F', 'Finalizado')], max_length=30)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.company')),
            ],
        ),
    ]
