# Generated by Django 4.1.7 on 2023-04-06 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="logo",
            field=models.ImageField(upload_to="company_logo"),
        ),
    ]
