# Generated by Django 4.1.7 on 2023-04-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0002_alter_company_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="company_size",
            field=models.CharField(
                choices=[
                    ("Micro", "Até 19 colaboradores"),
                    ("Pequena", "20 à 99 colaboradores"),
                    ("Media", "100 à 499 colaboradores"),
                    ("Grande", "Acima de 500 colaboradores"),
                ],
                default=1,
                max_length=30,
            ),
            preserve_default=False,
        ),
    ]
