# Generated by Django 4.1.7 on 2023-04-07 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0003_company_company_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
