# Generated by Django 4.1.7 on 2023-05-20 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0005_alter_jobs_position_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobs",
            name="url",
            field=models.URLField(default="NULL", max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="jobs",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="empresas.company"
            ),
        ),
    ]
