# Generated by Django 4.1.7 on 2023-05-20 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0006_jobs_url_alter_jobs_company"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobs",
            name="technologies_mastered",
        ),
        migrations.RemoveField(
            model_name="jobs",
            name="technologies_study",
        ),
    ]
